# Generated by Django 4.1.1 on 2022-09-09 18:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_editor', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(regex="^[A-z]+(([,.] |[ '-])[A-z]+)*(\\.?)( [IVXLCDM]+)?$")])),
                ('ddc_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\d{3}(\\.{1}\\d{1,9})?$')])),
                ('is_literature', models.BooleanField()),
                ('is_biography', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosegarden.book')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rosegarden.branch')),
            ],
        ),
    ]
