# Generated by Django 4.1.1 on 2022-10-08 20:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='BranchUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(blank=True, max_length=500, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rosegarden.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_editor', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(regex="^[A-z]+(([,.] |[ '-])[A-z]+)*(\\.?)( [IVXLCDM]+)?$")])),
                ('ddc_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\d{3}(\\.{1}\\d{1,9})?$')])),
                ('version', models.CharField(blank=True, max_length=200)),
                ('is_biography_or_memoir', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rosegarden.branch')),
            ],
            options={
                'verbose_name_plural': 'books',
            },
        ),
    ]
