# Generated by Django 4.1.1 on 2022-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosegarden', '0002_branchuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchuserprofile',
            name='interests',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
